/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'knjname' at '17/02/15 22:08' with Gradle 3.0
 *
 * @author knjname, @date 17/02/15 22:08
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
